# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_auto_20181013_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalyearstudents',
            name='message_id',
            field=models.CharField(max_length=255),
        ),
    ]
